<?php
$datos = array("Asignaturas" => array("12345" => array("nombre" => "Desarrollo Web en Entorno Servidor",
                                    "duracion" => "8h",
                                    "tipo" => "Troncal"),
                                    "23456" => array("nombre" => "Desarrollo Web en Entorno Cliente",
                                    "duracion" => "9h",
                                    "tipo" => "Troncal"),
                                    "34567" => array("nombre" => "Despliegue de Aplicaciones Web",
                                    "duracion" => "3h",
                                    "tipo" => "Obligatoria"),
                                    "45678" => array("nombre" => "Diseño de Interfaces Web",
                                    "duracion" => "6h",
                                    "tipo" => "Obligatoria"),
                                    "12345" => array("nombre" => "Empresa e Iniciativa Amprendedora",
                                    "duracion" => "4h",
                                    "tipo" => "Optativa")),
                "Profesores" => array("11111111A" => array("nombre" => "Juan Carlos",
                                    "apellidos" => "Jiménez Masegosa"),
                                    "22222222B" => array("nombre" => "José Antonio",
                                    "apellidos" => "Piñero Berbel"),
                                    "33333333C" => array("nombre" => "Alicia Desiree",
                                    "apellidos" => "Benítez Yáñez"),
                                    "44444444D" => array("nombre" => "Francisca",
                                    "apellidos" => "Molina Álvarez"),
                                    "55555555E" => array("nombre" => "José Manuel",
                                    "apellidos" => "Aranda Rodríguez"),
                                    "66666666F" => array("nombre" => "Alejandro",
                                    "apellidos" => "Viana Ríos"),
                                    "77777777G" => array("nombre" => "Lucas",
                                    "apellidos" => "Méndez"),
                                    "88888888H" => array("nombre" => "Armando",
                                    "apellidos" => "Garrido"),
                                    "99999999I" => array("nombre" => "Juan Carlos",
                                    "apellidos" => "Ramírez")),
                "ProfXAsig" => array("12345"));
?>